version: "3.8"
services:
    rabbitmq3:
        container_name: "rabbitmq"
        hostname: "rabbitmq"
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_DEFAULT_USER=myuser
            - RABBITMQ_DEFAULT_PASS=mypassword
        ports:
            # AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'
    
    message-service:
        container_name: "message-service"
        image: "message-service"
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - "8080:80"
        depends_on:
            - rabbitmq3
        environment:
            - ASPNETCORE_ENVIRONMENT=Local
            - AGGREGATED_MESSAGE_SERVER_URL=<insert-url>
            - RABBITMQ_USERNAME=myuser
            - RABBITMQ_PASSWORD=mypassword
            - RABBITMQ_HOSTNAME=rabbitmq
            - MAXIMUM_BATCH_SIZE=10
            - BATCH_POLL_INTERVAL=10000